### PR TITLE
Gradually upgrade crates to Rust 2018 edition

### PR DESCRIPTION
**Pull request by karim-agha**
This changeset upgrades `common-types` and `ethjson` to 2018 edition.

### CODE REVIEW

**Review by jomuel — APPROVED** [review]
lgtm

**Comment by karim-agha** [comment]
Don't merge this yet please, need to apply the fix from #312

**Comment by rakita** [comment]
Fix is already applied and merged in `dev`
for ethjson, change is already done in master, I will see to push `merge` commit to dev so that we can connect `main` and `dev` branched properly, this would make it easier in future to merge `dev` to `main` when we want to make new release.

**Comment by adria0** [comment]
`Submodule json_tests updated 6031 files` 

It's upgrading also the json_tests, I think that should be removed from this PR

**Pull request closed without merging**
