### PR TITLE
EIP-712: Update logos and rewrite type parser (builds on 1.53)

### PR DESCRIPTION
**Pull request by 717a56e1**
Lunarity lexer was causing build issues on Rust 1.53 due to a dependency on an very outdated version of logos, so I've removed that dependency and use Logos directly to parse the solidity types for EIP-712.

### CODE REVIEW

**Comment by 717a56e1** [comment]
This seems to resolve  #442 , my branch builds fine on `cargo 1.53.0 (4369396ce 2021-04-27)`.

**Comment by Tristan-Wilson** [comment]
`cargo build --release --features final` and `cargo test` pass for me now, thanks!

**Review by Voklen — APPROVED** [review]
Thank you, these changes fix the problem properly by using Logos directly. This fix has been tested by multiple people (Including myself) and no bugs have arisen.

**Comment by damelLP** [comment]
ETA on this getting merged?

**Comment by 717a56e1** [comment]
@damelLP, 

Looks like it has the approvals, needs someone with write access to merge @sunce86 @Voklen

**Review by rimrakhimov — APPROVED** [review]
@varasev The PR looks fine for me. I believe we may use it to resolve #547 and #442 as it provides simpler solution without necessity to maintain updated _lunarity_ repository.

**Comment by rimrakhimov** [comment]
@717a56e1 Could you please also commit updated `openethereum/Cargo.lock` file in order to support a build in CI/CD?

**Comment by varasev** [comment]
@rimrakhimov I updated `Cargo.lock` (successfully compiled on Rust 1.58.1).

**Pull request merged**
