### PR TITLE
Revert "Remove eth/63 protocol version (#252)"

### PR DESCRIPTION
**Pull request by rakita**
This reverts commit bbecb0415ef1ffe5d1c15d9a0fd19de859f0eb1a.

### CODE REVIEW

**Review by jomuel — APPROVED** [review]
lgtm

**Comment by adria0** [comment]
> This reverts commit [bbecb04](https://github.com/openethereum/openethereum/commit/bbecb0415ef1ffe5d1c15d9a0fd19de859f0eb1a).

Could you explain the reason for reverting the commit @rakita?

**Comment by ngyam** [comment]
@adria0 we at energyweb with our AuRa chains kinda look forward to this, our nodes still stuck at 2.5.x and migration paths to 3.x seem to be broken for us. First we'd need to upgrade to a version that has 63/64 too with no showstopper bugs.
We need to have both until we migrate so there is a smooth transition and our chains not get rekt in the process :grimacing:
I guess this PR would ensure that.

**Comment by rakita** [comment]
For kovan and energyweb it seems they don't have a big percentage of nodes that have support for `eth/`64 and they would need to have a transition from v2.5.13, it could be done with v3.1.1+(bugfix commit #318) but this seems like a simpler solution. 
@ngyam i would recommend you to cherry-pick this commit and use it on top of v3.2.1, v3.2.1 is tested and pushed for production.

**Review by adria0 — APPROVED** [review]
LGTM

**Pull request merged**
