### PR TITLE
Trace comment on new block inclusion

### PR DESCRIPTION
**Pull request by rakita**
Comment only commit.

### CODE REVIEW

**Comment by rakita** [comment]
it matches to this: https://openethereum.github.io/Trace-NewBlock

**Review by adria0 — CHANGES_REQUESTED** [review]
Some comments are marked for rustdoc (`///`) and anothers no (`//`), maybe better if all are in the same class.

**Comment by rakita** [comment]
changed to `/// t_nb`.

**Comment by rakita** [comment]
changes all to `//` because `///` make rust doc break.

**Review by adria0 — APPROVED** [review]

**Pull request merged**
