### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dhcn**
The newest version of rust can't compile successfully. so give a advice.

### CODE REVIEW

**Review by lordt4ever — APPROVED** [review]
[](url)

**Review by roninkaizen — APPROVED** [review]
lgtm

**Review by roninkaizen — APPROVED** [review]

**Review by roninkaizen — APPROVED** [review]

**Review by roninkaizen — APPROVED** [review]
agreed

**Review by roninkaizen — APPROVED** [review]

**Comment by rimrakhimov** [comment]
Compilation with the latest version of rust was restored in #463

**Pull request closed without merging**
