### PR TITLE
Adds eth_maxPriorityFeePerGas implementaiton

### LINKED ISSUE #552: Lack of eth_maxPriorityFeePerGas implementation on OE 3.3.0-rc.8.
Summary:

- **OpenEthereum version3.3.0-rc.8
- **Fully synchronized**:  yes
- **Network**: Volta (PoA, AuRa)

Issue:

Lack of eth_maxPriorityFeePerGas implementation on OE 3.3.0-rc.8.

We have recently upgraded our Volta test Chain to London, and received some community raised issues related to the lack of eth_maxPriorityFeePerGas implementation on OE. 

Are there any plans on introducing the above on OE? Maybe in future rc release ?

Information on that front will be an important input for the plan on our mainnet (EWC) London Hard fork release. 

Woudl you kindly please advise?

### PR DESCRIPTION
**Pull request by rimrakhimov**
Closes #552

Implements eth_maxPriorityFeePerGas RPC method. To calculate a fee, we take all transactions from the last 100 blocks and compute the actual fees paid to the miners in these transactions. Of which we take the median and return as a response.

### CODE REVIEW

**Review by varasev — COMMENTED** [review]
I think this RPC should respond with `EIP-1559 is not activated` if EIP-1559 is not enabled.

**Comment by rimrakhimov** [comment]
@varasev, added `EIP-1559 is not activated` error response

**Comment by varasev** [comment]
@rimrakhimov When running `cargo test --release --all` I see the following test failure:

```
failures:

---- chain::supplier::test::return_nodes stdout ----
thread 'chain::supplier::test::return_nodes' panicked at 'assertion failed: rlp_result.is_some()', crates/ethcore/sync/src/chain/supplier.rs:798:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    chain::supplier::test::return_nodes
```

It is not related to this PR (seems this is because the test engine is not AuRa), but I'd propose to fix it here to make tests complete and see that they work fine.

**Comment by varasev** [comment]
I tried to test it locally using https://github.com/poanetwork/posdao-test-setup and found that the RPC request crashes the node at block 7, 8, or 9. EIP-1559 is activated at block 8: https://github.com/poanetwork/posdao-test-setup/blob/efa657e91538ba895fc6f938381517324aef37fe/scripts/copy-spec.js#L29

Steps to reproduce:
1. Run this build with https://github.com/poanetwork/posdao-test-setup
2. Wait until block 7, 8, or 9.
3. Right after the block is created, send the request to the first validator node:

```
curl --data '{"method":"eth_maxPriorityFeePerGas","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8541
```

The node will crash with this panic message:

```
2021-11-23 14:47:15  http.worker00 WARN openethereum  Panic occured, see stderr for details


====================

   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: panic_hook::set_with::{{closure}}
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic::{{closure}}
   5: std::sys_common::backtrace::__rust_end_short_backtrace
   6: std::panicking::begin_panic
   7: <jsonrpc_core::delegates::DelegateAsyncMethod<T,F> as jsonrpc_core::calls::RpcMethod<M>>::call
   8: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
   9: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  10: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  11: <jsonrpc_http_server::handler::RpcHandler<M,S> as futures::future::Future>::poll
  12: <jsonrpc_http_server::handler::RpcHandler<M,S> as futures::future::Future>::poll
  13: <jsonrpc_http_server::handler::RpcHandler<M,S> as futures::future::Future>::poll
  14: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
  15: futures::future::option::<impl futures::future::Future for core::option::Option<F>>::poll
  16: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  17: tokio_threadpool::worker::Worker::run_task
  18: tokio_threadpool::worker::Worker::run
  19: tokio_reactor::with_default
  20: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  21: std::sys_common::backtrace::__rust_begin_short_backtrace
  22: core::ops::function::FnOnce::call_once{{vtable.shim}}
  23: std::sys::unix::thread::Thread::new::thread_start
  24: __pthread_body
  25: __pthread_start


Thread 'http.worker00' panicked at 'arithmetic operation overflow', /Users/vadim/.cargo/registry/src/github.com-1ecc6299db9ec823/primitive-types-0.7.2/src/lib.rs:32

This is a bug. Please report it at:

    https://github.com/openethereum/openethereum/issues/new


2021-11-23 14:47:15  main INFO openethereum::run  Finishing work, please wait...
Error: 1
```

**Review by varasev — APPROVED** [review]

**Pull request merged**
