### PR TITLE
ethstore - remove unnecessary dir & tiny-keccak dependencies from the lib

### PR DESCRIPTION
**Pull request by elpiel**
I've encountered a very ugly dependency issue trying with `journaldb` because the `dir` dependency, although not used by the lib crate, was included in the `lib.rs`.
This removes the `dir` dependency, as well as the `tiny-keccak` which is also not used.

Also a question: I see the dependencies are quite old and not update in a while. Will they be updated in the near future?

### CODE REVIEW

**Comment by elpiel** [comment]
Build didn't fail on changes made in the PR:

Screenshot from 2020-11-17 14-29-11

**Comment by rakita** [comment]
rebase to dev `set-env` should be fixed there.

**Comment by elpiel** [comment]
@rakita should I change to `dev` as base?

**Comment by rakita** [comment]
yep, we are merging things in `dev` first.

**Comment by elpiel** [comment]
Build failed on non-related to this PR issue:

**Comment by elpiel** [comment]
Build failed on non-related to this PR issue:
Screenshot from 2020-11-18 11-14-11

**Comment by elpiel** [comment]
:heavy_check_mark:  Build successfully passes

**Review by adria0 — APPROVED** [review]
LGTM

**Pull request merged**
