### PR TITLE
kvdb-* upgrade

### PR DESCRIPTION
**Pull request by mdben1247**
Builds on #253. Upgraded `kvdb-*`, `memory-db`, `trie-db`, `hash-db`, `parking_lot` libraries.

### CODE REVIEW

**Comment by adria0** [comment]
> Builds on #253. Upgraded `kvdb-*`, `memory-db`, `trie-db`, `hash-db`, `parking_lot` libraries.

@mdben1247, we had in the past a lot of performance regression problems updating the kvdb libraries. This change requires a full performance diff analysis, especially on disk usage.

**Comment by mdben1247** [comment]
As reported here #89, our own testing shows about 2x faster block syncing / verification times and execution for various rpc workloads. That's quite a lot actually. But of course, more testing is needed here, I'll be doing just that and report back.

**Comment by adria0** [comment]
> As reported here #89, our own testing shows about 2x faster block syncing / verification times and execution for various rpc workloads. That's quite a lot actually. But of course, more testing is needed here, I'll be doing just that and report back.

Please, check what happens when openetherum 3.0.0 used an updated version of the DB in https://etherscan.io/chartsync/chaindefault between may 26th and 14th jun.

**Comment by mdben1247** [comment]
> Please, check what happens when openetherum 3.0.0 used an updated version of the DB in https://etherscan.io/chartsync/chaindefault between may 26th and 14th jun.

I see what you mean. I've been mostly focused on speed for now. I'll take a better look at disk usage.

**Comment by mdben1247** [comment]
About disk usage. Newer `rocksdb` seem to use write ahead logs more extensively.

https://github.com/facebook/rocksdb/wiki/Write-Ahead-Log

By default there is some heuristics which determines the maximum total size of WAL and in my test case equals to a about 50GB (ie. a lot). The db size is then some 'normal' size plus WAL. At client startup the db will be cleaned up, so it starts with 'normal' size and zero WAL. As the client syncs WAL will grow and occasionally they are partially deleted, so the whole db size will be 'normal' size plus some variable amount of WAL. This seem to be the disk usage spikes that we see. If one doesn't care much about disk usage, this is all probably just fine. But if we do care, it would make sense to limit the size of WAL.

There is an option for that in `rocksdb`: [max_total_wal_size](https://github.com/facebook/rocksdb/blob/48bfca38f6f175435052a59791922a1a453d9609/include/rocksdb/options.h#L467). Unfortunately it is not exposed through `kvdb-rocksdb`. For testing purposes I merged a patched `kvdb-rocksdb 0.9.1` into the tree and added a command line option to the client to expose the setting `--db-max-wal-size`. My testing shows this limit is respected, WAL never exceed the max. While syncing 4-5 blocks/second, WAL reach 10GB after 15 minutes. So I am thinking a rather small max value (perhaps 4 GB) would be appropriate for normal operations. 

Of course this all needs a more testing. Rushing here seems unwise, however I think large performance gains of the newer `rocksdb` make this worthy of serious consideration.

**Comment by mdben1247** [comment]
PR to add max wal limit to `kvdb-rocksdb`: https://github.com/paritytech/parity-common/pull/528

**Comment by ytrezq** [comment]
@mdben1247 is this changed backward compatible? Or does if I test this pull request code, I will no longer be able to use the database with previous versions of OpenEthereum because of format changes?

**Comment by ytrezq** [comment]
I’m seeing it’s far to to be an up to date rocksdb version which is to be used. Recent versions added support for avx2 and the new `io_uring` low filesystem latency system call family.

**Comment by mdben1247** [comment]
> is this changed backward compatible? Or does if I test this pull request code, I will no longer be able to use the database with previous versions of OpenEthereum because of format changes?

I don't know, I haven't tried it myself. I'd strongly suggest backing up first.

> I’m seeing it’s far to to be an up to date rocksdb version which is to be used. Recent versions added support for avx2 and the new `io_uring` ultra low latency filesystem access system call family.

`openethereum` is using `kvdb-rocksdb` which doesn't use the latest `rocksdb` version. Long term I agree it would make sense to keep up with new versions, but there may be quite a lot of work involved.

**Comment by rakita** [comment]
Closing pull request in favor of: https://github.com/openethereum/openethereum/pull/332

**Pull request closed without merging**
