### PR TITLE
Add ws-max-paxload

### PR DESCRIPTION
**Pull request by mdben1247**
I made an issue #85 with patch attached. I've since learned that the proper github way would be to create a pull request. 

This adds an option to set `max-payload` for WS server. By setting a large enough `max-payload,` we can avoid errors with requests larger than the default 5MB:

`WS Error <Io(Custom { kind: InvalidInput, error: "Exceeded maximum buffer capacity" })>`

### CODE REVIEW

**Comment by adria0** [comment]
@mdben1247 could you set the merge target into `dev`, please?

**Comment by mdben1247** [comment]
I changed target to dev, but now there are other file changes and commits listed, beside my fix. I am not very familiar with git workflow. Should I make another branch off of dev and cherry-pick my commit there?

**Comment by adria0** [comment]
> I changed target to dev, but now there are other file changes and commits listed, beside my fix. I am not very familiar with git workflow. Should I make another branch off of dev and cherry-pick my commit there?

As you want, I usually merge & fix the conflicts.

**Comment by mdben1247** [comment]
I leave it as is, since it seems that I'd have to open another pull request for that.

**Comment by rakita** [comment]
I rebased it in here https://github.com/openethereum/openethereum/pull/155.
This pull request can be closed.

**Comment by roninkaizen** [comment]
need a description usage example, please :)
going in advance with @itchykitteh, maybe it works even without knowing which settings are allowed

**Pull request closed without merging**
