### PR TITLE
Add support for non-fork side of Phoenix

### PR DESCRIPTION
**Pull request by sorpaas**
In the past weeks I've got requests from @MGiuseppi and others that they want the non-fork side of Phoenix to be supported.

Geth has similar flags since Istanbul, to prepare for situations in case hard fork needs to be cancelled in an emergency situation. So this PR would be quite useful to avoid us needing to pull all-nights to prepare for emergency releases.

We tentatively agreed to add those flags in last OpenEthereum weekly meeting, but I guess the situation might have changed a little. xD (cc @Georgi87 @vorot93)

### CODE REVIEW

**Comment by q9f** [comment]
> Geth has similar flags since Istanbul

Indeed, on the call you suggested introducing the behavior of Geth could be beneficial.

```
~/.opt/byz-f/go-ethereum q9-config-testnet
❯ geth --help | grep -Ii override
  --override.istanbul value           Manually specify Istanbul fork-block, overriding the bundled setting (default: 0)
  --override.muirglacier value        Manually specify Muir Glacier fork-block, overriding the bundled setting (default: 0)
```

However, instead of passing an entirely new chain spec to the client and listing a new chain in the cli usage instructions, you could just provide an override as I assumed you were suggesting that on the last call.

```
CHAIN may be [...] ethereum, classic, classic-oppose-phoenix, [...]
```

Not sure if this will be well received. I believe adapting the Geth behavior here is more beneficial as it does not add dead weight to the client and can also be useful in other places, e.g., testing.

```
--chain classic --override-phoenix "0x7fffffff"
```

or

```
--chain foundation --override-istanbul "0x7fffffff"
```

**Comment by sorpaas** [comment]
> Not sure if this will be well received.

I'd just go with the simplest solution right now (as a new chain spec). What you're proposing will require supporting "groupped parameters", which we don't have yet.

**Comment by sorpaas** [comment]
I realized that I missed the precompile changes. Let me fix that before merging.

**Comment by sorpaas** [comment]
Updated diff:

```
diff --git a/classic.json b/classic_no_phoenix.json
index fd6ce73f4..85de09aa0 100644
--- a/classic.json
+++ b/classic_no_phoenix.json
@@ -40,14 +40,7 @@
 		"eip658Transition": "0x85d9a0",
 		"eip145Transition": "0x921288",
 		"eip1014Transition": "0x921288",
-		"eip1052Transition": "0x921288",
-		"eip1283Transition": "0x0",
-		"eip1283DisableTransition": "0x0",
-		"eip1283ReenableTransition": "0xa03ae7",
-		"eip1344Transition": "0xa03ae7",
-		"eip1706Transition": "0xa03ae7",
-		"eip1884Transition": "0xa03ae7",
-		"eip2028Transition": "0xa03ae7"
+		"eip1052Transition": "0x921288"
 	},
 	"genesis": {
 		"seal": {
@@ -4432,7 +4425,7 @@
 					"0x85d9a0": {
 						"price": { "alt_bn128_const_operations": { "price": 500 }}
 					},
-					"0xa03ae7": {
+					"0x7fffffffffffff": {
 						"price": { "alt_bn128_const_operations": { "price": 150 }}
 					}
 				}
@@ -4445,7 +4438,7 @@
 					"0x85d9a0": {
 						"price": { "alt_bn128_const_operations": { "price": 40000 }}
 					},
-					"0xa03ae7": {
+					"0x7fffffffffffff": {
 						"price": { "alt_bn128_const_operations": { "price": 6000 }}
 					}
 				}
@@ -4458,23 +4451,12 @@
 					"0x85d9a0": {
 						"price": { "alt_bn128_pairing": { "base": 100000, "pair": 80000 }}
 					},
-					"0xa03ae7": {
+					"0x7fffffffffffff": {
 						"price": { "alt_bn128_pairing": { "base": 45000, "pair": 34000 }}
 					}
 				}
 			}
 		},
-		"0x0000000000000000000000000000000000000009": {
-			"builtin": {
-				"name": "blake2_f",
-				"activate_at": "0xa03ae7",
-				"pricing": {
-					"blake2_f": {
-						"gas_per_round": 1
-					}
-				}
-			}
-		},
 		"3282791d6fd713f1e94f4bfd565eaa78b3a0599d": {
 			"balance": "1337000000000000000000"
 		},
```

**Pull request merged**
